### ISSUE TITLE
NTR: new term "Frameshift detected" under qc issues

### ISSUE THREAD

**Issue by ChanchalYa** [pha4ge/contextual_data_QC_tags#7]
# PHA4GE QC Contextual Data Tag Specification - New Term Request (NTR)

_May request multiple terms in a single issue - delete the fields irrelevant to your request._

We're annotating some PHAC datasets for public repo upload and want to use the PHA4GE QC tags but some of the genomes in our datasets have detected frameshifts reducing the overall quality. There doesn't seem to be an appropriate term for frameshifts in the quality control issues field. I had a chat with Emma Griffiths and we think a new term is needed to tag such genomes, details can be viewed below.

## New Field(s)

Label:
Definition/Description:
Definition Source:
Synonyms or alternative labels:
Additional Comments (not an annotation): 

## Picklist Item(s)

Associated Field(s): quality control issues
Parent Term: Not Applicable
Label: Frameshift detected
Definition/Description: The identification of frameshift mutations resulting in reduced overall genome quality.
Definition Source (reference, website): Emma Griffiths
Synonyms or alternative labels: Not Applicable
Additional Comments: Not Applicable

---
Contributor Attribution: {Optional - ORCiD is preferred}

Thanks!

**Comment by griffie** [comment]
New "quality control issues" tag added: excess frameshift mutations detected [GENEPIO:0100751]
